export const rajasthanData = [
  { "state": "Rajasthan", "district": "Ajmer", "latitude": 26.4499, "longitude": 74.6399 },
  { "state": "Rajasthan", "district": "Alwar", "latitude": 27.55299, "longitude": 76.63457 },
  { "state": "Rajasthan", "district": "Banswara", "latitude": 23.5461, "longitude": 74.4345 },
  { "state": "Rajasthan", "district": "Baran", "latitude": 25.1, "longitude": 76.5167 },
  { "state": "Rajasthan", "district": "Barmer", "latitude": 25.75, "longitude": 71.3833 },
  { "state": "Rajasthan", "district": "Bharatpur", "latitude": 27.2173, "longitude": 77.4895 },
  { "state": "Rajasthan", "district": "Bhilwara", "latitude": 25.3463, "longitude": 74.6364 },
  { "state": "Rajasthan", "district": "Bikaner", "latitude": 28.0229, "longitude": 73.3119 },
  { "state": "Rajasthan", "district": "Bundi", "latitude": 25.4448, "longitude": 75.6373 },
  { "state": "Rajasthan", "district": "Chittorgarh", "latitude": 24.8790, "longitude": 74.6290 },
  { "state": "Rajasthan", "district": "Churu", "latitude": 28.2920, "longitude": 74.9618 },
  { "state": "Rajasthan", "district": "Dausa", "latitude": 26.8910, "longitude": 76.3350 },
  { "state": "Rajasthan", "district": "Dholpur", "latitude": 26.7025, "longitude": 77.8956 },
  { "state": "Rajasthan", "district": "Dungarpur", "latitude": 23.8431, "longitude": 73.7147 },
  { "state": "Rajasthan", "district": "Hanumangarh", "latitude": 29.5810, "longitude": 74.3294 },
  { "state": "Rajasthan", "district": "Jaipur", "latitude": 26.9124, "longitude": 75.7873 },
  { "state": "Rajasthan", "district": "Jaisalmer", "latitude": 26.9157, "longitude": 70.9083 },
  { "state": "Rajasthan", "district": "Jalore", "latitude": 25.35, "longitude": 72.6167 },
  { "state": "Rajasthan", "district": "Jhalawar", "latitude": 24.5965, "longitude": 76.1608 },
  { "state": "Rajasthan", "district": "Jhunjhunu", "latitude": 28.1289, "longitude": 75.3978 },
  { "state": "Rajasthan", "district": "Jodhpur", "latitude": 26.2389, "longitude": 73.0243 },
  { "state": "Rajasthan", "district": "Karauli", "latitude": 26.4983, "longitude": 77.0150 },
  { "state": "Rajasthan", "district": "Kota", "latitude": 25.2138, "longitude": 75.8648 },
  { "state": "Rajasthan", "district": "Nagaur", "latitude": 27.2000, "longitude": 73.7333 },
  { "state": "Rajasthan", "district": "Pali", "latitude": 25.7711, "longitude": 73.3234 },
  { "state": "Rajasthan", "district": "Pratapgarh", "latitude": 24.0300, "longitude": 74.7833 },
  { "state": "Rajasthan", "district": "Rajsamand", "latitude": 25.0667, "longitude": 73.8833 },
  { "state": "Rajasthan", "district": "Sawai Madhopur", "latitude": 26.0230, "longitude": 76.3441 },
  { "state": "Rajasthan", "district": "Sikar", "latitude": 27.6094, "longitude": 75.1399 },
  { "state": "Rajasthan", "district": "Sirohi", "latitude": 24.8826, "longitude": 72.8588 },
  { "state": "Rajasthan", "district": "Tonk", "latitude": 26.1667, "longitude": 75.7833 },
  { "state": "Rajasthan", "district": "Udaipur", "latitude": 24.5854, "longitude": 73.7125 }
]


export const states = [
  { "code": "AN", "name": "Andaman and Nicobar Islands" },
  { "code": "AP", "name": "Andhra Pradesh" },
  { "code": "AR", "name": "Arunachal Pradesh" },
  { "code": "AS", "name": "Assam" },
  { "code": "BR", "name": "Bihar" },
  { "code": "CH", "name": "Chandigarh" },
  { "code": "CT", "name": "Chhattisgarh" },
  { "code": "DN", "name": "Dadra and Nagar Haveli and Daman and Diu" },
  { "code": "DL", "name": "Delhi" },
  { "code": "GA", "name": "Goa" },
  { "code": "GJ", "name": "Gujarat" },
  { "code": "HR", "name": "Haryana" },
  { "code": "HP", "name": "Himachal Pradesh" },
  { "code": "JK", "name": "Jammu and Kashmir" },
  { "code": "JH", "name": "Jharkhand" },
  { "code": "KA", "name": "Karnataka" },
  { "code": "KL", "name": "Kerala" },
  { "code": "LA", "name": "Ladakh" },
  { "code": "LD", "name": "Lakshadweep" },
  { "code": "MP", "name": "Madhya Pradesh" },
  { "code": "MH", "name": "Maharashtra" },
  { "code": "MN", "name": "Manipur" },
  { "code": "ML", "name": "Meghalaya" },
  { "code": "MZ", "name": "Mizoram" },
  { "code": "NL", "name": "Nagaland" },
  { "code": "OR", "name": "Odisha" },
  { "code": "PY", "name": "Puducherry" },
  { "code": "PB", "name": "Punjab" },
  { "code": "RJ", "name": "Rajasthan" },
  { "code": "SK", "name": "Sikkim" },
  { "code": "TN", "name": "Tamil Nadu" },
  { "code": "TG", "name": "Telangana" },
  { "code": "TR", "name": "Tripura" },
  { "code": "UP", "name": "Uttar Pradesh" },
  { "code": "UT", "name": "Uttarakhand" },
  { "code": "WB", "name": "West Bengal" }
]
